name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags following the pattern v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  # Specify the version of .NET you are using

      - name: Restore dependencies
        run: dotnet restore src/NorthernNerds.Aspire.Neo4j.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/NorthernNerds.Aspire.Neo4j.csproj

      - name: Pack
        run: dotnet pack --configuration Release --no-restore --output ./nupkg src/NorthernNerds.Aspire.Neo4j.csproj

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
